name: Welcome

on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

permissions:
  issues: write
  pull-requests: write

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |
            Thanks for opening your first issue! 👋 We appreciate you taking the time to report this.

            If this is a bug, please make sure to include:
            - macOS version
            - Steps to reproduce
            - Expected vs actual behavior

            Check out our [CONTRIBUTING.md](https://github.com/jeanluciradukunda/Clipy/blob/main/CONTRIBUTING.md) for guidelines.
          pr-message: |
            Thanks for your first pull request! 🎉

            Please make sure:
            - [ ] The build passes (`Cmd+B` in Xcode)
            - [ ] SwiftLint has no new warnings
            - [ ] You've tested the change manually

            A maintainer will review this shortly.
